spring:
  mail:
    host: smtp.163.com
    port: 465
    username: dmregy@163.com
    password: VPbQ2X9N2gM6PANi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
          starttls:
            enable: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.laoliu.system.controller

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: YourEndpoint
    access-key-id: YourAccessKeyId
    access-key-secret: YourAccessKeySecret
    bucket-name: YourBucketName