spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cas_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: 6379

file:
  upload:
    path: /app/uploads/
    server-address: http://${SERVER_ADDRESS:localhost}:8080
